appProjects:
    # Name will be used for the Argo CD AppProject and the Namespace the
    # applications will be deployed into
  - name: acm-policy

    # Description for the project
    description: "ACM policies for OpenShift cluster management"

    # Display name for the project
    displayName: "ACM Policy"

    # URL to a Git repo with application Helm charts for this project. This URL
    # should end in ".git"
    gitUrl: "https://github.com/hello-world-gitops/policy.git"

    # Git branch to pull charts from. Default: "main"
    gitBranch: main

    # Helm values file to use relative to each helm chart. Default: "values.yaml"
    valuesFile: values.yaml

    # List of applications to deploy into the project
    applications:
        # Name of the application. THIS MUST BE UNIQUE! Even if deployed into a
        # different project, Argo CD Application names must be unique
      - name: acm-policy

        # Path inside the project gitUrl to the Helm chart. Use "." if the
        # chart is in the root of the repo. Use a relative path otherwise
        gitPath: '.'
